spring:
  profiles:
    active:
    - dev

---
server:
  port: 8882
  
spring:
  profiles: dev
  application:
    name: config-client-dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
server:
  port: 8883
  
spring:
  profiles: test
  application:
    name: config-client-test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
server:
  port: 8885
  
spring:
  profiles: prod
  application:
    name: config-client--prod
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/
